spring:
  application:
    name: Goodbooks
  config:
    import:
      - "application-persistence.yaml"
      - "application-client.yaml"
  output:
    ansi:
      enabled: ALWAYS
info:
  component: Real World Application
  version: 0.0.1
server:
  port: 9090