spring:
  application:
    name: Goodbooks
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibarnate.dialect.PostgreSQLDialect
      properties:
        hibernate:
          default_schema: good_books
  datasource:
    url: "jdbc:postgresql://localhost:5432/goodbooks"
    username: realworld
    password: realworld
info:
  component: Real World Application
  version: 0.0.1
server:
  port: 9090