version: "3.2"

services:
  db:
    container_name: realworld-postgresql
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - real-network
    environment:
      POSTGRES_DB: goodbooks
      POSTGRES_USER: realworld
      POSTGRES_PASSWORD: realworld
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: realworld-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: goodbook@realworld.com
      PGADMIN_DEFAULT_PASSWORD: realworld
    ports:
      - "8081:80"
    networks:
      - real-network

networks:
  real-network:
    driver: bridge