spring:
 jpa:
  hibernate:
    ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: good_books
datasource:
  url: "jdbc:postgresql://localhost:5432/goodbooks"
  username: realworld
  password: realworld